// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int64            `json:"id"`
	ApiKey      string           `json:"api_key"`
	ClientID    pgtype.Int8      `json:"client_id"`
	UserGroupID pgtype.Int8      `json:"user_group_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Chamber struct {
	ID             int64            `json:"id"`
	DoorNumber     pgtype.Int4      `json:"door_number"`
	Row            pgtype.Int4      `json:"row"`
	Column         pgtype.Int4      `json:"column"`
	Side           pgtype.Int4      `json:"side"`
	MachineID      int64            `json:"machine_id"`
	IsFull         pgtype.Bool      `json:"is_full"`
	CylinderID     pgtype.Int8      `json:"cylinder_id"`
	IsCylinderFull bool             `json:"is_cylinder_full"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type ChamberHistory struct {
	ID             int64            `json:"id"`
	ChamberID      int64            `json:"chamber_id"`
	LoadID         pgtype.Int8      `json:"load_id"`
	OrderID        pgtype.Int8      `json:"order_id"`
	UserID         pgtype.Int8      `json:"user_id"`
	IsFull         bool             `json:"is_full"`
	CylinderID     pgtype.Int8      `json:"cylinder_id"`
	IsCylinderFull bool             `json:"is_cylinder_full"`
	Event          pgtype.Int4      `json:"event"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Client struct {
	ID        int64            `json:"id"`
	ParentID  pgtype.Int8      `json:"parent_id"`
	Title     string           `json:"title"`
	FullTitle pgtype.Text      `json:"full_title"`
	FleetID   string           `json:"fleet_id"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Command struct {
	ID                int64            `json:"id"`
	MachineID         int64            `json:"machine_id"`
	OrderID           pgtype.Int8      `json:"order_id"`
	UserID            pgtype.Int8      `json:"user_id"`
	Command           string           `json:"command"`
	Data              []byte           `json:"data"`
	Response          pgtype.Text      `json:"response"`
	Sent              pgtype.Bool      `json:"sent"`
	Timeout           int32            `json:"timeout"`
	FailIfNotReady    bool             `json:"fail_if_not_ready"`
	WaitForResponse   bool             `json:"wait_for_response"`
	WaitForConnection int32            `json:"wait_for_connection"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Counter struct {
	ID    int32  `json:"id"`
	Type  string `json:"type"`
	Count int32  `json:"count"`
}

type Credit struct {
	ID              int64            `json:"id"`
	OriginalOrderID pgtype.Int8      `json:"original_order_id"`
	OrderID         pgtype.Int8      `json:"order_id"`
	ClientID        int64            `json:"client_id"`
	IsValid         bool             `json:"is_valid"`
	Amount          pgtype.Numeric   `json:"amount"`
	UserID          pgtype.Int8      `json:"user_id"`
	Code            string           `json:"code"`
	ExpiryDate      pgtype.Timestamp `json:"expiry_date"`
	Note            pgtype.Text      `json:"note"`
	MachineID       pgtype.Int8      `json:"machine_id"`
	CylinderID      pgtype.Int8      `json:"cylinder_id"`
	CreatorID       pgtype.Int8      `json:"creator_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type CreditUsage struct {
	ID        int64            `json:"id"`
	CreditID  int64            `json:"credit_id"`
	OrderID   int64            `json:"order_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CurrencyRate struct {
	Currency  string           `json:"currency"`
	Rate      pgtype.Numeric   `json:"rate"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Cylinder struct {
	ID               int64            `json:"id"`
	GasType          pgtype.Int4      `json:"gas_type"`
	Title            string           `json:"title"`
	ShortTitle       pgtype.Text      `json:"short_title"`
	DetectionTitle   string           `json:"detection_title"`
	IllegalAboveRow  pgtype.Int4      `json:"illegal_above_row"`
	Image            pgtype.Text      `json:"image"`
	ClientID         int64            `json:"client_id"`
	Capacity         pgtype.Numeric   `json:"capacity"`
	DisplayCapacity  pgtype.Text      `json:"display_capacity"`
	ContractRequired pgtype.Bool      `json:"contract_required"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type DetectionAttempt struct {
	ID                 int64            `json:"id"`
	OrderID            int64            `json:"order_id"`
	CylinderID         pgtype.Int8      `json:"cylinder_id"`
	Image              pgtype.Text      `json:"image"`
	DetectedIdentifier pgtype.Text      `json:"detected_identifier"`
	Confidence         pgtype.Numeric   `json:"confidence"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type ExternalCylinder struct {
	CylinderID      int64            `json:"cylinder_id"`
	ExternalID      string           `json:"external_id"`
	EmptyCylinderID pgtype.Text      `json:"empty_cylinder_id"`
	GasID           pgtype.Text      `json:"gas_id"`
	Title           pgtype.Text      `json:"title"`
	CylinderTitle   pgtype.Text      `json:"cylinder_title"`
	GasTitle        pgtype.Text      `json:"gas_title"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type ExternalMachine struct {
	MachineID   int64            `json:"machine_id"`
	ExternalID  pgtype.Text      `json:"external_id"`
	Title       pgtype.Text      `json:"title"`
	TerminalID  pgtype.Text      `json:"terminal_id"`
	StoreNumber pgtype.Text      `json:"store_number"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type FillOrder struct {
	ID             int64            `json:"id"`
	CreatedByID    int64            `json:"created_by_id"`
	AssignedToID   int64            `json:"assigned_to_id"`
	TruckID        int64            `json:"truck_id"`
	Notes          pgtype.Text      `json:"notes"`
	TravelDocument pgtype.Text      `json:"travel_document"`
	Status         int32            `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type FillOrderCylinder struct {
	ID          int64            `json:"id"`
	FillOrderID int64            `json:"fill_order_id"`
	CylinderID  int64            `json:"cylinder_id"`
	MachineID   int64            `json:"machine_id"`
	Count       int32            `json:"count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type FixOrder struct {
	ID           int64            `json:"id"`
	CreatedByID  int64            `json:"created_by_id"`
	AssignedToID pgtype.Int8      `json:"assigned_to_id"`
	MachineID    int64            `json:"machine_id"`
	Status       int32            `json:"status"`
	Notes        pgtype.Text      `json:"notes"`
	Issue        string           `json:"issue"`
	Action       pgtype.Text      `json:"action"`
	Documents    pgtype.Text      `json:"documents"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Load struct {
	ID          int64            `json:"id"`
	MachineID   int64            `json:"machine_id"`
	UserID      pgtype.Int8      `json:"user_id"`
	FillOrderID pgtype.Int8      `json:"fill_order_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Machine struct {
	ID             int64            `json:"id"`
	ClientID       int64            `json:"client_id"`
	ApiKey         string           `json:"api_key"`
	Title          string           `json:"title"`
	Number         pgtype.Int4      `json:"number"`
	Url            pgtype.Text      `json:"url"`
	GroupID        pgtype.Int8      `json:"group_id"`
	ManagementID   pgtype.Text      `json:"management_id"`
	Type           int32            `json:"type"`
	LayoutID       int32            `json:"layout_id"`
	TerminalID     pgtype.Text      `json:"terminal_id"`
	Secret         pgtype.Text      `json:"secret"`
	NeedsAttention pgtype.Bool      `json:"needs_attention"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type MachineAddress struct {
	ID        int64            `json:"id"`
	MachineID int64            `json:"machine_id"`
	Address   pgtype.Text      `json:"address"`
	Region    pgtype.Text      `json:"region"`
	Point     interface{}      `json:"point"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MachineCylinder struct {
	ID                  int64            `json:"id"`
	CylinderID          int64            `json:"cylinder_id"`
	MachineGroupID      int64            `json:"machine_group_id"`
	Min                 int32            `json:"min"`
	Target              pgtype.Int4      `json:"target"`
	Order               int32            `json:"order"`
	MissingCapPenalty   pgtype.Numeric   `json:"missing_cap_penalty"`
	MissingValvePenalty pgtype.Numeric   `json:"missing_valve_penalty"`
	MissingLabelPenalty pgtype.Numeric   `json:"missing_label_penalty"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type MachineGroup struct {
	ID        int64            `json:"id"`
	ClientID  int64            `json:"client_id"`
	Title     string           `json:"title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MachineGroupHistory struct {
	ID        int64            `json:"id"`
	MachineID int64            `json:"machine_id"`
	GroupID   pgtype.Int8      `json:"group_id"`
	UserID    int64            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type MachineLock struct {
	ID          int64            `json:"id"`
	MachineID   int64            `json:"machine_id"`
	UserID      int64            `json:"user_id"`
	Locked      bool             `json:"locked"`
	LockMessage pgtype.Text      `json:"lock_message"`
	LockReason  pgtype.Text      `json:"lock_reason"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type MachineNote struct {
	ID        int64            `json:"id"`
	MachineID int64            `json:"machine_id"`
	UserID    int64            `json:"user_id"`
	Note      pgtype.Text      `json:"note"`
	IsPublic  bool             `json:"is_public"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MachinePart struct {
	ID            int64       `json:"id"`
	MachineID     pgtype.Int8 `json:"machine_id"`
	PartVersionID int64       `json:"part_version_id"`
}

type MachineStatus struct {
	ID                    int64            `json:"id"`
	MachineID             int64            `json:"machine_id"`
	MaintainerID          pgtype.Int8      `json:"maintainer_id"`
	Status                int32            `json:"status"`
	DoorStatus            []byte           `json:"door_status"`
	GasSensorStatus       []byte           `json:"gas_sensor_status"`
	FanStatus             []byte           `json:"fan_status"`
	PrinterStatus         []byte           `json:"printer_status"`
	PaymentTerminalStatus []byte           `json:"payment_terminal_status"`
	CarouselStatus        []byte           `json:"carousel_status"`
	CameraStatus          []byte           `json:"camera_status"`
	Error                 pgtype.Text      `json:"error"`
	LastStatusChange      pgtype.Timestamp `json:"last_status_change"`
	OrderID               pgtype.Int8      `json:"order_id"`
	LoadID                pgtype.Int8      `json:"load_id"`
	LastEvent             pgtype.Text      `json:"last_event"`
	Component             pgtype.Text      `json:"component"`
	Locked                pgtype.Bool      `json:"locked"`
	RebootLock            pgtype.Bool      `json:"reboot_lock"`
	HasCriticalError      pgtype.Bool      `json:"has_critical_error"`
}

type MachineUser struct {
	ID          int64            `json:"id"`
	UserGroupID int64            `json:"user_group_id"`
	MachineID   pgtype.Int8      `json:"machine_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Notification struct {
	ID                 int64            `json:"id"`
	ClientID           int64            `json:"client_id"`
	MachineID          pgtype.Int8      `json:"machine_id"`
	Title              string           `json:"title"`
	NotificationTypeID int64            `json:"notification_type_id"`
	Level              int32            `json:"level"`
	Content            string           `json:"content"`
	Read               pgtype.Bool      `json:"read"`
	Seen               pgtype.Bool      `json:"seen"`
	Metadata           []byte           `json:"metadata"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type NotificationTemplate struct {
	ID          int64            `json:"id"`
	Level       int32            `json:"level"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type NotificationType struct {
	ID   int64       `json:"id"`
	Type pgtype.Text `json:"type"`
}

type NotificationUsage struct {
	ID                 int64            `json:"id"`
	ClientID           int64            `json:"client_id"`
	Channel            pgtype.Int4      `json:"channel"`
	NotificationTypeID int64            `json:"notification_type_id"`
	OrderID            pgtype.Int8      `json:"order_id"`
	UserID             pgtype.Int8      `json:"user_id"`
	MachineID          pgtype.Int8      `json:"machine_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID                  int64            `json:"id"`
	MachineID           int64            `json:"machine_id"`
	ClientID            int64            `json:"client_id"`
	InCylinderID        pgtype.Int8      `json:"in_cylinder_id"`
	OutCylinderID       pgtype.Int8      `json:"out_cylinder_id"`
	InChamberID         pgtype.Int8      `json:"in_chamber_id"`
	OutChamberID        pgtype.Int8      `json:"out_chamber_id"`
	RequestedPrice      pgtype.Numeric   `json:"requested_price"`
	VoucherCode         pgtype.Text      `json:"voucher_code"`
	AbortReason         pgtype.Text      `json:"abort_reason"`
	Type                pgtype.Int4      `json:"type"`
	Paid                pgtype.Bool      `json:"paid"`
	Delivered           pgtype.Bool      `json:"delivered"`
	CylinderReturned    pgtype.Bool      `json:"cylinder_returned"`
	Status              int32            `json:"status"`
	FeedbackScore       pgtype.Int4      `json:"feedback_score"`
	UserID              pgtype.Int8      `json:"user_id"`
	CreditCode          pgtype.Text      `json:"credit_code"`
	CreatorID           pgtype.Int8      `json:"creator_id"`
	CanExchange         bool             `json:"can_exchange"`
	InCylinderValidated pgtype.Bool      `json:"in_cylinder_validated"`
	RetryCode           pgtype.Text      `json:"retry_code"`
	IsMobile            pgtype.Bool      `json:"is_mobile"`
	PriceHistoryID      pgtype.Int8      `json:"price_history_id"`
	Metadata            []byte           `json:"metadata"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type OrderEvent struct {
	ID            int64            `json:"id"`
	OrderID       pgtype.Int8      `json:"order_id"`
	UserID        pgtype.Int8      `json:"user_id"`
	EventType     pgtype.Text      `json:"event_type"`
	EventData     []byte           `json:"event_data"`
	NeedAttention pgtype.Bool      `json:"need_attention"`
	Error         pgtype.Text      `json:"error"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type OrderNote struct {
	ID        int64            `json:"id"`
	OrderID   pgtype.Int8      `json:"order_id"`
	UserID    pgtype.Int8      `json:"user_id"`
	Note      string           `json:"note"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Part struct {
	ID          int64       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

type PartVersion struct {
	ID          int64       `json:"id"`
	PartID      int64       `json:"part_id"`
	Version     pgtype.Text `json:"version"`
	Description pgtype.Text `json:"description"`
}

type Payment struct {
	ID              int64            `json:"id"`
	OrderID         int64            `json:"order_id"`
	PaymentMethodID pgtype.Int8      `json:"payment_method_id"`
	ReferenceToken  string           `json:"reference_token"`
	Amount          pgtype.Numeric   `json:"amount"`
	Status          int32            `json:"status"`
	Error           pgtype.Text      `json:"error"`
	Receipt         pgtype.Text      `json:"receipt"`
	ReceiptUrl      pgtype.Text      `json:"receipt_url"`
	ReceiptNumber   pgtype.Text      `json:"receipt_number"`
	PaymentIntentID pgtype.Text      `json:"payment_intent_id"`
	Metadata        []byte           `json:"metadata"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type PaymentMethod struct {
	ID        int64            `json:"id"`
	MachineID int64            `json:"machine_id"`
	ConfigID  pgtype.Int8      `json:"config_id"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type PaymentMethodConfig struct {
	ID               int64            `json:"id"`
	ClientID         int64            `json:"client_id"`
	Title            string           `json:"title"`
	Method           pgtype.Int4      `json:"method"`
	IsCancelable     pgtype.Bool      `json:"is_cancelable"`
	IsAutoRefundable pgtype.Bool      `json:"is_auto_refundable"`
	RefundType       int32            `json:"refund_type"`
	RefundLimitType  int32            `json:"refund_limit_type"`
	RefundLimitValue pgtype.Int4      `json:"refund_limit_value"`
	IsActive         pgtype.Bool      `json:"is_active"`
	Metadata         pgtype.Text      `json:"metadata"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Permission struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Price struct {
	ID             int64            `json:"id"`
	InCylinderID   pgtype.Int8      `json:"in_cylinder_id"`
	OutCylinderID  int64            `json:"out_cylinder_id"`
	MachineGroupID int64            `json:"machine_group_id"`
	ScheduleID     pgtype.Int8      `json:"schedule_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type PriceAdjustment struct {
	ID        int64            `json:"id"`
	OrderID   pgtype.Int8      `json:"order_id"`
	Type      string           `json:"type"`
	Value     string           `json:"value"`
	Amount    pgtype.Numeric   `json:"amount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type PriceHistory struct {
	ID        int64            `json:"id"`
	PriceID   int64            `json:"price_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	IsActive  pgtype.Bool      `json:"is_active"`
	UserID    pgtype.Int8      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Refund struct {
	ID           int64            `json:"id"`
	PaymentID    int64            `json:"payment_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Status       int32            `json:"status"`
	Error        pgtype.Text      `json:"error"`
	Receipt      pgtype.Text      `json:"receipt"`
	ReceiptUrl   pgtype.Text      `json:"receipt_url"`
	RefundedByID pgtype.Int8      `json:"refunded_by_id"`
	Metadata     []byte           `json:"metadata"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Reserve struct {
	ID         int64            `json:"id"`
	UserID     pgtype.Int8      `json:"user_id"`
	OrderID    pgtype.Int8      `json:"order_id"`
	CylinderID int64            `json:"cylinder_id"`
	MachineID  int64            `json:"machine_id"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	UsedAt     pgtype.Timestamp `json:"used_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Schedule struct {
	ID        int64            `json:"id"`
	Title     pgtype.Text      `json:"title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ScheduleItem struct {
	ID         int64            `json:"id"`
	ScheduleID int64            `json:"schedule_id"`
	StartAt    pgtype.Timestamp `json:"start_at"`
	EndAt      pgtype.Timestamp `json:"end_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Truck struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Capacity  int32            `json:"capacity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type TruckLocation struct {
	ID          int64            `json:"id"`
	FillOrderID pgtype.Int8      `json:"fill_order_id"`
	TruckID     int64            `json:"truck_id"`
	Point       interface{}      `json:"point"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            int64            `json:"id"`
	FullName      string           `json:"full_name"`
	Email         string           `json:"email"`
	EmailVerified pgtype.Bool      `json:"email_verified"`
	Phone         pgtype.Text      `json:"phone"`
	PhoneVerified pgtype.Bool      `json:"phone_verified"`
	Password      string           `json:"password"`
	Role          int32            `json:"role"`
	TwoFactorType pgtype.Int4      `json:"two_factor_type"`
	TotpSecret    pgtype.Text      `json:"totp_secret"`
	ClientID      pgtype.Int8      `json:"client_id"`
	GroupID       pgtype.Int8      `json:"group_id"`
	IsActive      pgtype.Bool      `json:"is_active"`
	DefaultPin    pgtype.Text      `json:"default_pin"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type UserGroup struct {
	ID        int64            `json:"id"`
	Title     string           `json:"title"`
	ClientID  int64            `json:"client_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserNotification struct {
	ID                 int64 `json:"id"`
	NotificationTypeID int64 `json:"notification_type_id"`
	UserID             int64 `json:"user_id"`
	Email              bool  `json:"email"`
	Sms                bool  `json:"sms"`
}

type UserPermission struct {
	ID           int64            `json:"id"`
	PermissionID int64            `json:"permission_id"`
	UserGroupID  int64            `json:"user_group_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Voucher struct {
	ID             int64            `json:"id"`
	PriceID        pgtype.Int8      `json:"price_id"`
	MachineGroupID pgtype.Int8      `json:"machine_group_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	Reason         pgtype.Text      `json:"reason"`
	Count          int32            `json:"count"`
	Code           pgtype.Text      `json:"code"`
	CanStack       pgtype.Bool      `json:"can_stack"`
	IsActive       pgtype.Bool      `json:"is_active"`
	ScheduleID     pgtype.Int8      `json:"schedule_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type VoucherCylinder struct {
	ID         int64            `json:"id"`
	VoucherID  pgtype.Int8      `json:"voucher_id"`
	CylinderID pgtype.Int8      `json:"cylinder_id"`
	Count      int32            `json:"count"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type VoucherMachineGroup struct {
	ID             int64            `json:"id"`
	VoucherID      pgtype.Int8      `json:"voucher_id"`
	MachineGroupID pgtype.Int8      `json:"machine_group_id"`
	Count          pgtype.Int4      `json:"count"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type VoucherPaymentMethod struct {
	ID              int64            `json:"id"`
	VoucherID       pgtype.Int8      `json:"voucher_id"`
	PaymentMethodID pgtype.Int8      `json:"payment_method_id"`
	Count           pgtype.Int4      `json:"count"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type VoucherUsage struct {
	ID        int64       `json:"id"`
	VoucherID pgtype.Int8 `json:"voucher_id"`
	UserID    pgtype.Int8 `json:"user_id"`
	OrderID   pgtype.Int8 `json:"order_id"`
	Redeemed  pgtype.Bool `json:"redeemed"`
}

type Wishlist struct {
	ID                 int64            `json:"id"`
	UserID             int64            `json:"user_id"`
	CylinderID         int64            `json:"cylinder_id"`
	MachineID          int64            `json:"machine_id"`
	NotificationTypeID int64            `json:"notification_type_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}
