// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, email_verified, phone, phone_verified, password, role, two_factor_type, totp_secret, client_id, group_id, is_active, default_pin, created_at, updated_at FROM "user"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.Role,
		&i.TwoFactorType,
		&i.TotpSecret,
		&i.ClientID,
		&i.GroupID,
		&i.IsActive,
		&i.DefaultPin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
