// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: machine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Machines_CreateMachine_FullMethodName = "/pb.Machines/CreateMachine"
)

// MachinesClient is the client API for Machines service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MachinesClient interface {
	CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*MachineResponse, error)
}

type machinesClient struct {
	cc grpc.ClientConnInterface
}

func NewMachinesClient(cc grpc.ClientConnInterface) MachinesClient {
	return &machinesClient{cc}
}

func (c *machinesClient) CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...grpc.CallOption) (*MachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineResponse)
	err := c.cc.Invoke(ctx, Machines_CreateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachinesServer is the server API for Machines service.
// All implementations must embed UnimplementedMachinesServer
// for forward compatibility.
type MachinesServer interface {
	CreateMachine(context.Context, *CreateMachineRequest) (*MachineResponse, error)
	mustEmbedUnimplementedMachinesServer()
}

// UnimplementedMachinesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachinesServer struct{}

func (UnimplementedMachinesServer) CreateMachine(context.Context, *CreateMachineRequest) (*MachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMachine not implemented")
}
func (UnimplementedMachinesServer) mustEmbedUnimplementedMachinesServer() {}
func (UnimplementedMachinesServer) testEmbeddedByValue()                  {}

// UnsafeMachinesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachinesServer will
// result in compilation errors.
type UnsafeMachinesServer interface {
	mustEmbedUnimplementedMachinesServer()
}

func RegisterMachinesServer(s grpc.ServiceRegistrar, srv MachinesServer) {
	// If the following call pancis, it indicates UnimplementedMachinesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Machines_ServiceDesc, srv)
}

func _Machines_CreateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachinesServer).CreateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Machines_CreateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachinesServer).CreateMachine(ctx, req.(*CreateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Machines_ServiceDesc is the grpc.ServiceDesc for Machines service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Machines_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Machines",
	HandlerType: (*MachinesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMachine",
			Handler:    _Machines_CreateMachine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "machine.proto",
}
